import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import Providers from '@/components/providers';
import Header from "@/components/header";
import Footer from "@/components/footer";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from 'next-intl';

const inter = Inter({subsets:['latin'], variable:'--font-sans'})
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif'
  
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn('flex min-h-screen flex-col font-sans antialiased',
          inter.variable,
          playfair.variable
        )}
      >
        <NextIntlClientProvider messages={messages}>
        <Providers>
          <Header />
          <main className="grow">
            {children}
          </main>
          <Footer />
        </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
